x = 5;
print (type(x));
x = 20.7
print (type(x));
x = 1j
print (type(x));
x = ["Apple", "Banana", "Cherry", "Grapes"];
print (x);
print (type(x));

x= ("Apple", "Banana", "Cherry", "Grapes");
print (x);
print (type(x));

x= {"Apple", "Banana", "Cherry", "Grapes"};
print (x);
print (type(x));


x = {"Name" : "Vineet", "Age" : 35, "Address" : "Gurugaon", "Pin" : 122002};
print (x);
print (type (x))



x = 1;
y = 4.8;
z = 1j;
print (type(x));
print (type(y));
print (type(z));